# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f958dad810e10203b1450683cbbe6622258e486c49dce0c4f0d6ae6272dbbacd1331b1dc04633b7c47206456e4c9ca7dd0a0d507f3219d5fe92036be1ca94011

test:
  secret_key_base: 47263848e7ee3ab7040c82058177a0075d95e12e960aba06cc774f82936a1c4e24da424a7fa0ae1603b68e26445c00b15bd3baaf237ee2c7cda4e7a2ab32d26b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
